### ISSUE TITLE
Whether new library support old qsp format?

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [QSPFoundation/qsp#9]
Hello everybody. Several years ago after update of the library old games in android player not worked correct,and downgrading qsp library fix this problem. But,as i understand,you will do,or did,what qsp library support old qsp syntaks and new. Whether it true,or no. You haven't discussions on github,so i create this issue,to ask question to you via issue. Also i,as blind,want to ask you add in qsp field accessibilityText for main and varsdesc and methods to get it via qsp library. It can be usefull,for example,if we have some images or very difficult table,which allows to solve some puzzle. In this case author of game will ad,if want,accessibility information for maindesc and (or) varsdesc,and (or) actions,variants,locations,etc,and i can get it via methods of qsp library. In this case visual part of interface will save without any changes for site. Also please add flag accessibility,and methods in library,to get/set this flag. game developer can check,whether it true and if yes,do some changes for game.

For now qsp games,in my opinion,one of the most accessible games for blind.

**Comment by AlexandrKozlovskiy** [comment]
@hzdbyte Ok,library still not fully support old syntaks. Because i thought,what in new version you added support for old syntaks,but,as i understand,it not,so it no sence to ask @seedhartha to update library,because he even downgraded it,because alot of games use old syntaks. About accessibility,it a very large subject. If you want,we can cammunicate privately,and i will explain to you about accessibility more details via [telegram.](https://t.me/sashablr_1994)

**Comment by goodvin** [comment]
I agree it'd be great to improve accessibility of the old player, but as I said it's in maintenance mode.
So most likely new features/big improvements won't be added to the existing classic player.
Have you tried to use qspider? This is a new web-based player & Im curious if it works for you.

**Comment by hzdbyte** [comment]
I agree it'd be great to improve accessibility of the old player, but as I said it's in maintenance mode.
So most likely new features/big improvements won't be added to the existing classic player.
Have you tried to use qspider? This is a new web-based player & Im curious if it works for you.

**Comment by hzdbyte** [comment]
I hope qSpider solves these issues.
