### ISSUE TITLE
Add Github `Releases`

### ISSUE THREAD

**Issue by Korb** [QSPFoundation/qsp#99]
https://github.com/QSPFoundation/qsp/releases

Now:

> There aren’t any releases here
> You can create a release to package software, along with release notes and links to binary files, for other people to use. Learn more about releases in [our docs](https://docs.github.com/repositories/releasing-projects-on-github/about-releases).

For players who are not programmers and do not have the tools to compile, it is much more convenient to download a package with binaries from the releases section than to look for them somewhere else.

**Comment by hzdbyte** [comment]
This repository contains source code of the engine / core library, different players (i.e. user applications) are located at other repositories:
https://github.com/QSPFoundation/qspgui
https://github.com/QSPFoundation/qspider
